package com.rkade;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.util.List;
import java.util.logging.Logger;

public class ButtonsPanel extends BaseForm implements DeviceListener, ActionListener, FocusListener, ChangeListener {
    private final static Logger logger = Logger.getLogger(ButtonsPanel.class.getName());
    private final List<JButton> switchButtons;
    private JPanel mainButtonPanel;
    private JPanel bottomPanel;
    private JPanel topPanel;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;
    private JButton button8;
    private JButton button9;
    private JButton button10;
    private JButton button11;
    private JButton button12;
    private JButton button13;
    private JButton button14;
    private JButton button15;
    private JButton button16;
    private JButton button17;
    private JButton button18;
    private JButton button19;
    private JButton button20;
    private JButton button21;
    private JButton button22;
    private JButton button23;
    private JButton button24;
    private JButton button25;
    private JButton button26;
    private JButton button27;
    private JButton button28;
    private JButton button29;
    private JButton button30;
    private JButton button31;
    private JButton button32;


    private Device device = null;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public ButtonsPanel() {
        controls = List.of();
        switchButtons = List.of(button1, button2, button3, button4, button5, button6, button7, button8,
                button9, button10, button11, button12, button13, button14, button15, button16,
                button17, button18, button19, button20, button21, button22, button23, button24,
                button25, button26, button27, button28, button29, button30, button31, button32);

        setPanelEnabled(false);
        setupControlListener();
    }

    @Override
    public void deviceAttached(Device device) {
        this.device = device;
        setPanelEnabled(true);
    }

    @Override
    public void deviceDetached(Device device) {
        this.device = null;
        setPanelEnabled(false);
    }

    @Override
    public void deviceUpdated(Device device, String status, DataReport report) {
        if (report != null) {
            if (report.getReportType() == Device.DATA_REPORT_ID) {
                if (report instanceof ButtonsDataReport buttonsDataReport) {
                    updateControls(buttonsDataReport);
                }
            }
        }
    }

    private boolean getButtonState(ButtonsDataReport buttonsDataReport, long buttonIndex) {
        //return buttonsDataReport.getButtonState(buttonIndex);
        return ((buttonsDataReport.getButtonsState() & (long) Math.pow(2, buttonIndex)) > 0);
    }

    private void updateControls(ButtonsDataReport buttonsDataReport) {
        for (JButton button : switchButtons) {
            button.setSelected(getButtonState(buttonsDataReport, switchButtons.indexOf(button)));
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        boolean status = handleAction(e);
        if (!status) {
            logger.warning("Action failed for:" + e.getActionCommand());
        }
    }

    private boolean handleAction(ActionEvent e) {
        return true;
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if (device != null) {
            boolean status = true;
            if (!status) {
                logger.warning("State Changed, failed for:" + e.getSource());
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainButtonPanel = new JPanel();
        mainButtonPanel.setLayout(new BorderLayout(0, 0));
        mainButtonPanel.setAutoscrolls(false);
        mainButtonPanel.setMaximumSize(new Dimension(400, 240));
        mainButtonPanel.setMinimumSize(new Dimension(400, 240));
        mainButtonPanel.setName("mainButtonPanel");
        mainButtonPanel.setPreferredSize(new Dimension(400, 240));
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bottomPanel.setMaximumSize(new Dimension(400, 50));
        bottomPanel.setMinimumSize(new Dimension(100, 35));
        bottomPanel.setPreferredSize(new Dimension(400, 45));
        mainButtonPanel.add(bottomPanel, BorderLayout.CENTER);

        final JLabel label1 = new JLabel();
        label1.setAlignmentY(1.0f);
        label1.setHorizontalAlignment(2);
        label1.setMinimumSize(new Dimension(200, 25));
        label1.setPreferredSize(new Dimension(226, 17));
        label1.setText("Debounce  (0-255)");
        bottomPanel.add(label1);
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        topPanel.setAutoscrolls(false);
        topPanel.setMaximumSize(new Dimension(200, 205));
        topPanel.setMinimumSize(new Dimension(100, 205));
        topPanel.setPreferredSize(new Dimension(200, 205));
        mainButtonPanel.add(topPanel, BorderLayout.NORTH);
        button1 = new JButton();
        button1.setAutoscrolls(false);
        button1.setEnabled(false);
        button1.setHorizontalAlignment(0);
        button1.setMinimumSize(new Dimension(50, 50));
        button1.setPreferredSize(new Dimension(50, 50));
        button1.setSelected(false);
        button1.setText("1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        topPanel.add(button1, gbc);
        button2 = new JButton();
        button2.setAutoscrolls(false);
        button2.setEnabled(false);
        button2.setMinimumSize(new Dimension(50, 50));
        button2.setPreferredSize(new Dimension(50, 50));
        button2.setSelected(false);
        button2.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        topPanel.add(button2, gbc);
        button3 = new JButton();
        button3.setAutoscrolls(false);
        button3.setEnabled(false);
        button3.setMinimumSize(new Dimension(50, 50));
        button3.setPreferredSize(new Dimension(50, 50));
        button3.setRolloverEnabled(false);
        button3.setSelected(false);
        button3.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        topPanel.add(button3, gbc);
        button4 = new JButton();
        button4.setAutoscrolls(false);
        button4.setEnabled(false);
        button4.setMinimumSize(new Dimension(50, 50));
        button4.setPreferredSize(new Dimension(50, 50));
        button4.setRolloverEnabled(false);
        button4.setSelected(false);
        button4.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        topPanel.add(button4, gbc);
        button5 = new JButton();
        button5.setAutoscrolls(false);
        button5.setEnabled(false);
        button5.setMinimumSize(new Dimension(50, 50));
        button5.setPreferredSize(new Dimension(50, 50));
        button5.setRolloverEnabled(false);
        button5.setSelected(false);
        button5.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        topPanel.add(button5, gbc);
        button6 = new JButton();
        button6.setAutoscrolls(false);
        button6.setEnabled(false);
        button6.setMinimumSize(new Dimension(50, 50));
        button6.setPreferredSize(new Dimension(50, 50));
        button6.setRolloverEnabled(false);
        button6.setSelected(false);
        button6.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        topPanel.add(button6, gbc);
        button7 = new JButton();
        button7.setAutoscrolls(false);
        button7.setEnabled(false);
        button7.setMinimumSize(new Dimension(50, 50));
        button7.setPreferredSize(new Dimension(50, 50));
        button7.setRolloverEnabled(false);
        button7.setSelected(false);
        button7.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        topPanel.add(button7, gbc);
        button8 = new JButton();
        button8.setAutoscrolls(false);
        button8.setEnabled(false);
        button8.setMinimumSize(new Dimension(50, 50));
        button8.setPreferredSize(new Dimension(50, 50));
        button8.setRolloverEnabled(false);
        button8.setSelected(false);
        button8.setText("8");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        topPanel.add(button8, gbc);
        button16 = new JButton();
        button16.setAutoscrolls(false);
        button16.setEnabled(false);
        button16.setHorizontalAlignment(0);
        button16.setMinimumSize(new Dimension(50, 50));
        button16.setPreferredSize(new Dimension(50, 50));
        button16.setSelected(false);
        button16.setText("16");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 1;
        topPanel.add(button16, gbc);
        button15 = new JButton();
        button15.setAutoscrolls(false);
        button15.setEnabled(false);
        button15.setHorizontalAlignment(0);
        button15.setMinimumSize(new Dimension(50, 50));
        button15.setPreferredSize(new Dimension(50, 50));
        button15.setSelected(false);
        button15.setText("15");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        topPanel.add(button15, gbc);
        button14 = new JButton();
        button14.setAutoscrolls(false);
        button14.setEnabled(false);
        button14.setHorizontalAlignment(0);
        button14.setMinimumSize(new Dimension(50, 50));
        button14.setPreferredSize(new Dimension(50, 50));
        button14.setSelected(false);
        button14.setText("14");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        topPanel.add(button14, gbc);
        button13 = new JButton();
        button13.setAutoscrolls(false);
        button13.setEnabled(false);
        button13.setHorizontalAlignment(0);
        button13.setMinimumSize(new Dimension(50, 50));
        button13.setPreferredSize(new Dimension(50, 50));
        button13.setSelected(false);
        button13.setText("13");
        button13.setToolTipText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        topPanel.add(button13, gbc);
        button12 = new JButton();
        button12.setAutoscrolls(false);
        button12.setEnabled(false);
        button12.setHorizontalAlignment(0);
        button12.setMinimumSize(new Dimension(50, 50));
        button12.setPreferredSize(new Dimension(50, 50));
        button12.setSelected(false);
        button12.setText("12");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        topPanel.add(button12, gbc);
        button9 = new JButton();
        button9.setAutoscrolls(false);
        button9.setEnabled(false);
        button9.setHorizontalAlignment(0);
        button9.setMinimumSize(new Dimension(50, 50));
        button9.setPreferredSize(new Dimension(50, 50));
        button9.setSelected(false);
        button9.setText("9");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        topPanel.add(button9, gbc);
        button10 = new JButton();
        button10.setAutoscrolls(false);
        button10.setEnabled(false);
        button10.setHorizontalAlignment(0);
        button10.setMinimumSize(new Dimension(50, 50));
        button10.setPreferredSize(new Dimension(50, 50));
        button10.setSelected(false);
        button10.setText("10");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        topPanel.add(button10, gbc);
        button11 = new JButton();
        button11.setAutoscrolls(false);
        button11.setEnabled(false);
        button11.setHorizontalAlignment(0);
        button11.setMinimumSize(new Dimension(50, 50));
        button11.setPreferredSize(new Dimension(50, 50));
        button11.setSelected(false);
        button11.setText("11");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        topPanel.add(button11, gbc);
        button17 = new JButton();
        button17.setAutoscrolls(false);
        button17.setEnabled(false);
        button17.setHorizontalAlignment(0);
        button17.setMinimumSize(new Dimension(50, 50));
        button17.setPreferredSize(new Dimension(50, 50));
        button17.setSelected(false);
        button17.setText("17");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        topPanel.add(button17, gbc);
        button25 = new JButton();
        button25.setAutoscrolls(false);
        button25.setEnabled(false);
        button25.setHorizontalAlignment(0);
        button25.setMinimumSize(new Dimension(50, 50));
        button25.setPreferredSize(new Dimension(50, 50));
        button25.setSelected(false);
        button25.setText("25");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        topPanel.add(button25, gbc);
        button18 = new JButton();
        button18.setAutoscrolls(false);
        button18.setEnabled(false);
        button18.setHorizontalAlignment(0);
        button18.setMinimumSize(new Dimension(50, 50));
        button18.setPreferredSize(new Dimension(50, 50));
        button18.setSelected(false);
        button18.setText("18");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        topPanel.add(button18, gbc);
        button26 = new JButton();
        button26.setAutoscrolls(false);
        button26.setEnabled(false);
        button26.setHorizontalAlignment(0);
        button26.setMinimumSize(new Dimension(50, 50));
        button26.setPreferredSize(new Dimension(50, 50));
        button26.setSelected(false);
        button26.setText("26");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        topPanel.add(button26, gbc);
        button19 = new JButton();
        button19.setAutoscrolls(false);
        button19.setEnabled(false);
        button19.setHorizontalAlignment(0);
        button19.setMinimumSize(new Dimension(50, 50));
        button19.setPreferredSize(new Dimension(50, 50));
        button19.setSelected(false);
        button19.setText("19");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        topPanel.add(button19, gbc);
        button27 = new JButton();
        button27.setAutoscrolls(false);
        button27.setEnabled(false);
        button27.setHorizontalAlignment(0);
        button27.setMinimumSize(new Dimension(50, 50));
        button27.setPreferredSize(new Dimension(50, 50));
        button27.setSelected(false);
        button27.setText("27");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        topPanel.add(button27, gbc);
        button20 = new JButton();
        button20.setAutoscrolls(false);
        button20.setEnabled(false);
        button20.setHorizontalAlignment(0);
        button20.setMinimumSize(new Dimension(50, 50));
        button20.setPreferredSize(new Dimension(50, 50));
        button20.setSelected(false);
        button20.setText("20");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        topPanel.add(button20, gbc);
        button28 = new JButton();
        button28.setAutoscrolls(false);
        button28.setEnabled(false);
        button28.setHorizontalAlignment(0);
        button28.setMinimumSize(new Dimension(50, 50));
        button28.setPreferredSize(new Dimension(50, 50));
        button28.setSelected(false);
        button28.setText("28");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        topPanel.add(button28, gbc);
        button21 = new JButton();
        button21.setAutoscrolls(false);
        button21.setEnabled(false);
        button21.setHorizontalAlignment(0);
        button21.setMinimumSize(new Dimension(50, 50));
        button21.setPreferredSize(new Dimension(50, 50));
        button21.setSelected(false);
        button21.setText("21");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        topPanel.add(button21, gbc);
        button29 = new JButton();
        button29.setAutoscrolls(false);
        button29.setEnabled(false);
        button29.setHorizontalAlignment(0);
        button29.setMinimumSize(new Dimension(50, 50));
        button29.setPreferredSize(new Dimension(50, 50));
        button29.setSelected(false);
        button29.setText("29");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        topPanel.add(button29, gbc);
        button22 = new JButton();
        button22.setAutoscrolls(false);
        button22.setEnabled(false);
        button22.setHorizontalAlignment(0);
        button22.setMinimumSize(new Dimension(50, 50));
        button22.setPreferredSize(new Dimension(50, 50));
        button22.setSelected(false);
        button22.setText("22");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        topPanel.add(button22, gbc);
        button30 = new JButton();
        button30.setAutoscrolls(false);
        button30.setEnabled(false);
        button30.setHorizontalAlignment(0);
        button30.setMinimumSize(new Dimension(50, 50));
        button30.setPreferredSize(new Dimension(50, 50));
        button30.setSelected(false);
        button30.setText("30");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 3;
        topPanel.add(button30, gbc);
        button23 = new JButton();
        button23.setAutoscrolls(false);
        button23.setEnabled(false);
        button23.setHorizontalAlignment(0);
        button23.setMinimumSize(new Dimension(50, 50));
        button23.setPreferredSize(new Dimension(50, 50));
        button23.setSelected(false);
        button23.setText("23");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        topPanel.add(button23, gbc);
        button31 = new JButton();
        button31.setAutoscrolls(false);
        button31.setEnabled(false);
        button31.setHorizontalAlignment(0);
        button31.setMinimumSize(new Dimension(50, 50));
        button31.setPreferredSize(new Dimension(50, 50));
        button31.setSelected(false);
        button31.setText("31");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        topPanel.add(button31, gbc);
        button24 = new JButton();
        button24.setAutoscrolls(false);
        button24.setEnabled(false);
        button24.setHorizontalAlignment(0);
        button24.setMinimumSize(new Dimension(50, 50));
        button24.setPreferredSize(new Dimension(50, 50));
        button24.setSelected(false);
        button24.setText("24");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 2;
        topPanel.add(button24, gbc);
        button32 = new JButton();
        button32.setAutoscrolls(false);
        button32.setEnabled(false);
        button32.setHorizontalAlignment(0);
        button32.setMinimumSize(new Dimension(50, 50));
        button32.setPreferredSize(new Dimension(50, 50));
        button32.setSelected(false);
        button32.setText("32");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 3;
        topPanel.add(button32, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainButtonPanel;
    }

}
