package com.rkade;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import java.util.logging.Logger;

public class GainPanel extends BaseForm implements DeviceListener, ActionListener, FocusListener, ChangeListener {
    private final static Logger logger = Logger.getLogger(GainPanel.class.getName());
    private JPanel gainPanel;
    private short gainIndex;
    private Device device = null;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GainPanel() {
        controls = List.of();
        setPanelEnabled(false);
        setupControlListener();
        gainPanel.add(new AxisPanel());
    }

    @Override
    public void deviceAttached(Device device) {
        this.device = device;
        setPanelEnabled(true);
    }

    @Override
    public void deviceDetached(Device device) {
        this.device = null;
        setPanelEnabled(false);
    }

    @Override
    public void deviceUpdated(Device device, String status, DataReport report) {
        if (report != null) {
            if (report.getReportType() == Device.DATA_REPORT_ID) {
                if (report instanceof GainsDataReport gainsDataReport) {
                    updateControls(gainsDataReport);
                }
            }
        }
    }

    private void updateControls(GainsDataReport gainsDataReport) {

    }

    @Override
    public void focusLost(FocusEvent e) {
        boolean status = handleFocusLost(e);
        if (!status) {
            logger.warning("Focus lost, failed for:" + e.getSource());
        }
    }

    private boolean handleFocusLost(FocusEvent e) {
        return true;
    }

    @Override
    public void stateChanged(ChangeEvent e) {
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gainPanel = new JPanel();
        gainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gainPanel.setMinimumSize(new Dimension(562, 41));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gainPanel;
    }

}
